import { openAIClient } from "./OpenAIClient";
import {
    AI_TOOLS,
    AI_TOOL_HANDLERS,
} from "./AIToolRegistry";
import { ADMIN_ASSISTANT_INSTRUCTIONS } from "./prompts/admin-assistant.prompt";
import { AIRequestContext } from "./types/AIRequestContext";

export class AIService {

    async chat(
        message: string,
        context: AIRequestContext
    ): Promise<string> {

        let input: any[] = [
            {
                role: "user",
                content: message,
            },
        ];

        for (let iteration = 0; iteration < 10; iteration++) {

            const response = await openAIClient.responses.create({
                model: "gpt-5.6",

                instructions: ADMIN_ASSISTANT_INSTRUCTIONS,

                tools: AI_TOOLS,

                input,
            });

            input.push(...response.output);

            const functionCalls = response.output.filter(
                (item) => item.type === "function_call"
            );

            /**
             * No tool call means OpenAI has generated
             * the final response.
             */
            if (functionCalls.length === 0) {
                return response.output_text;
            }

            /**
             * Execute all requested tools.
             */
            for (const functionCall of functionCalls) {

                const toolName = functionCall.name;

                const handler =
                    AI_TOOL_HANDLERS[
                        toolName as keyof typeof AI_TOOL_HANDLERS
                    ];

                /**
                 * Tool is not registered.
                 */
                if (!handler) {
                    throw new Error(
                        `No handler registered for AI tool: ${toolName}`
                    );
                }

                /**
                 * Parse tool arguments generated by OpenAI.
                 */
                let args: unknown;

                try {

                    args = JSON.parse(
                        functionCall.arguments
                    );

                } catch {

                    throw new Error(
                        `Invalid arguments received for AI tool: ${toolName}`
                    );
                }

                /**
                 * Execute the actual Workdesk24 backend tool.
                 *
                 * Any service/database error is caught here
                 * so that one tool failure does not crash
                 * the complete AI conversation.
                 */
                let result: unknown;

                try {

                    result = await handler(
                        args as never,
                        context
                    );

                } catch (error) {

                    console.error(
                        `AI tool execution failed: ${toolName}`,
                        error
                    );

                    result = {
                        success: false,
                        error: "Unable to retrieve the requested data.",
                    };
                }

                /**
                 * Send the tool result back to OpenAI.
                 */
                input.push({
                    type: "function_call_output",
                    call_id: functionCall.call_id,
                    output: JSON.stringify(result),
                });
            }
        }

        /**
         * Prevent infinite tool-calling loops.
         */
        throw new Error(
            "AI tool execution exceeded maximum iterations."
        );
    }
}

export const aiService = new AIService();